#!/bin/sh



printDictStructure() {
echo "All files print: "
echo ""
for file in $(find "$1" -mindepth 1)
do
	if [[ ! -d "$file" ]] ; then
		echo "$file"
	fi
done

echo ""
echo "All dir print: "

for file in $(find "$1" -mindepth 1)
do
	if [[ -d "$file" ]] ; then
		echo "$file"
	fi
done

}


printDictStructure "fortests"


echo ""
echo ""
echo ""
echo ""
echo "modify -r -u fortests rose jutro monday bob"
bash modify -r -u fortests rose jutro monday bob
printDictStructure "fortests"


echo ""
echo ""
echo ""
echo ""
echo "modify -r -l fortests ROSE JUTRO MONDAY BOB"
bash modify -r -l fortests ROSE JUTRO MONDAY BOB
printDictStructure "fortests"


echo ""
echo ""
echo ""
echo ""
echo "modify -u fortests chocolate sweet"
bash modify -u fortests chocolate sweet
printDictStructure "fortests"


echo ""
echo ""
echo ""
echo ""
echo "modify -l fortests CHOCOLATE SWEET"
bash modify -l fortests CHOCOLATE SWEET
printDictStructure "fortests"


echo ""
echo ""
echo ""
echo ""
echo "modify -r s/e/QW/ fortests chocolate sweet bob frankes"
bash modify -r s/e/QW/ fortests chocolate sweet bob frankes
printDictStructure "fortests"


echo ""
echo ""
echo ""
echo ""
echo "modify -r s/QW/e/ fortests chocolate sweet bob"
bash modify -r s/QW/e/ fortests chocolatQW swQWet bob frankQWs
printDictStructure "fortests"


echo ""
echo ""
echo ""
echo ""
echo "modify -h"
bash modify -h



echo ""
echo ""
echo ""
echo ""
echo "modify -l -r fortests/school => such path does not exist:"
bash modify -l -r fortests/school rose



echo ""
echo ""
echo ""
echo ""
echo "modify -r -u fortests/school => such path does not exist:"
bash modify -r -u fortests/school rose



echo ""
echo ""
echo ""
echo ""
echo "modify -u fortests/school => such path does not exist:"
bash modify -u fortests/school rose



echo ""
echo ""
echo ""
echo ""
echo "modify -l fortests/school => such path does not exist:"
bash modify -l fortests/school rose



echo ""
echo ""
echo ""
echo ""
echo "modify -r s/e/FK/ fortests/school => such path does not exist:"
bash modify -r "s/e/FK/" fortests/school rose


echo ""
echo ""
echo ""
echo ""
echo "modify s/e/FK/ fortests => incorrect sed pattern:"
bash modify "s/e/FK/gkgh/lgl" fortests/school rose



echo ""
echo ""
echo ""
echo ""
echo "Output for no arguments"
bash modify



echo ""
echo ""
echo ""
echo ""
echo "modify -u -u -u -u fortests chocolate sweet"
bash modify -u -u -u -u fortests chocolate sweet


